version: "3.6"

services:
  construct:
    build: .
    command: meow-service
    depends_on:
      - postgres
      - nats
    ports:
      - "8080"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
      NATS_ADDRESS: nats:4222
  query:
    build: .
    command: query-service
    depends_on:
      - postgres
      - nats
    ports:
      - 8080
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: geges
      POSTGRES_PASSWORD: "password"
      NATS_ADDRESS: nats:4222
      ELASTICSEARCH_ADDRESS: elasticsearch:9200
  sender:
    build: .
    command: sender
    depends_on:
      - nats
    ports:
      - 8080
    environment:
      NATS_ADDRESS: nats:4222
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "geges"
      POSTGRES_PASSWORD: "password"
      NATS_ADDRESS: streaming:4222
  nats:
    image: nats-streaming:0.17.0
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - construct
      - query
      - sender